import type { CampaignStatus } from './type';

const CAMPAIGN_STATUS: Record<CampaignStatus, CampaignStatus> = {
  RECRUITING: 'RECRUITING',
  RECRUITMENT_CLOSED: 'RECRUITMENT_CLOSED',
  REMITTANCE_REQUEST: 'REMITTANCE_REQUEST',
  PURCHASING: 'PURCHASING',
  PICKUP_AVAILABLE: 'PICKUP_AVAILABLE',
  COMPLETED: 'COMPLETED',
} as const;

const CAMPAIGN_STATUS_LIST: Array<CampaignStatus> = [
  CAMPAIGN_STATUS.RECRUITING,
  CAMPAIGN_STATUS.RECRUITMENT_CLOSED,
  CAMPAIGN_STATUS.REMITTANCE_REQUEST,
  CAMPAIGN_STATUS.PURCHASING,
  CAMPAIGN_STATUS.PICKUP_AVAILABLE,
  CAMPAIGN_STATUS.COMPLETED,
] as const;

export { CAMPAIGN_STATUS, CAMPAIGN_STATUS_LIST };
